# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
