# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('bitrhday', models.CharField(max_length=8)),
                ('about', models.CharField(max_length=1024)),
                ('photo_link', models.CharField(max_length=1024)),
                ('facebook_link', models.CharField(max_length=1024)),
            ],
        ),
    ]
